version: '3'
services:
  node:
    build: .
    command: "npm run start"
    working_dir: /Chatbot/
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
    expose:
      - "3333"
    ports:
      - "3333:3333"
    volumes:
      - /home/devinectar.com.br/chatbot/conversas/:/Chatbot/arquivos
    container_name: tschatbot-api
    restart: always
