version: '3'
services:
  node:
    build: .
    command: "npm run start"
    working_dir: /Chatbot/
    environment:
      - NODE_ENV=production
    expose:
      - "9000"
    ports:
      - "9000:9000"
    container_name: chatbot-api
    restart: always
